// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Produccion", b =>
                {
                    b.Property<int>("ProduccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProduccionId");

                    b.ToTable("Produccion");
                });

            modelBuilder.Entity("ProduccionDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProduccionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("ProduccionId");

                    b.ToTable("ProduccionDetalle");
                });

            modelBuilder.Entity("Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 5,
                            Costo = 10m,
                            Descripcion = "Mani",
                            Existencia = 20,
                            Precio = 100m
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 10m,
                            Descripcion = "nuez",
                            Existencia = 15,
                            Precio = 100m
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 10m,
                            Descripcion = "almendra",
                            Existencia = 100,
                            Precio = 100m
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 10m,
                            Descripcion = "chia",
                            Existencia = 10,
                            Precio = 100m
                        },
                        new
                        {
                            ProductoId = 6,
                            Costo = 10m,
                            Descripcion = "pasas",
                            Existencia = 10,
                            Precio = 100m
                        });
                });

            modelBuilder.Entity("ProduccionDetalle", b =>
                {
                    b.HasOne("Produccion", null)
                        .WithMany("ProduccionDetalle")
                        .HasForeignKey("ProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Produccion", b =>
                {
                    b.Navigation("ProduccionDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
